const jCategory = [
    {
        index : 0,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Google_%22G%22_logo.svg/1200px-Google_%22G%22_logo.svg.png",
        title:"Web Developer",
        rate: '$900-1200/m',
        av: 'Full Time',
        companyName:"Google",
        location: "USA",
        vacancy: '01',
        hours:"50h/week",
        description:"At Google, we build products and services that help billions of people daily. Our mission is to organize the world’s information and make it universally accessible and useful. We’re a company that thrives on innovation, creativity, and collaboration, encouraging Googlers to think big and solve meaningful problems.",
        workplace:"Work from Home",
        experience:"2 to 5 years(s)"
    },
    {
        index : 1,
        image: "https://www.logo.wine/a/logo/Uber/Uber-Logo.wine.svg",
        title:"Freelancer",
        rate: '$900-1200/m',
        av: 'Freelancer',
        companyName:"Uber",
        location: "San Francisco",
        vacancy: '04',
        hours:"20h/week",
        description:"Uber's mission is to create opportunity through movement. We are a technology platform that connects the physical world with the digital world, creating new possibilities for people and new business models.",
        workplace:"Hybrid",
        experience:"1 to 3 years(s)"
    },
    {
        index : 2,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/500px-LinkedIn_logo_initials.png",
        title:"Buisness Associate",
        rate: '$900-1200/m',
        av: 'Part Time',
        companyName:"Linkedin",
        location: "Germany",
        vacancy: '05',
        hours:"15h/week",
        description:"LinkedIn's vision is to create economic opportunity for every member of the global workforce. The Product Marketing team is crucial to this mission, shaping the narrative of our products and connecting them with millions of professionals and businesses worldwide. We are looking for a strategic marketer to drive the growth of our flagship Sales Solutions portfolio.",
        workplace:"Hybrid",
        experience:"1 to 5 years(s)"
    },
    {
        index : 3,
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Facebook_f_logo_%282021%29.svg/2048px-Facebook_f_logo_%282021%29.svg.png",
        title:"Digital Marketing",
        rate: '$900-1200/m',
        av: 'Full Time',
        companyName:"Facebook",
        location: "London",
        vacancy: '06',
        hours:"12h/week",
        description:"At Meta, we are building the future of connection. Reality Labs is at the heart of this mission, developing the hardware and software that will bring the metaverse to life. We are looking for talented engineers who are passionate about building innovative products on a global scale",
        workplace:"Hybrid",
        experience:"1 to 3 years(s)"
    },

    {
        index : 4,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Instagram_logo_2016.svg/198px-Instagram_logo_2016.svg.png",
        title:"Product Designer",
        rate: '$900-1200/m',
        av: 'Part Time',
        companyName:"Instagram",
        location: "USA",
        vacancy: '07',
        hours:"15h/week",
        description:"Instagrams mission is to bring you closer to the people and things you love. As a Product Manager, you will be at the center of this mission, shaping the future of visual communication for a global community. We are looking for an experienced and creative product leader to drive the evolution of Reels, one of our most important and fastest-growing products.",
        workplace:"Hybrid",
        experience:"1 to 2 years(s)"
    },
    {
        index: 5,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/768px-Microsoft_logo.svg.png",
        title: "Data Analyst",
        rate: '$1,200-1,600/m',
        av: 'Full Time',
        companyName: "Microsoft",
        location: "Remote",
        vacancy: '03',
        hours: "40h/week",
        description: "Join Microsoft to transform data into insights that drive business decisions. You will build dashboards, analyze large datasets, and collaborate with cross-functional teams to deliver measurable impact.",
        workplace: "Remote",
        experience: "2 to 4 years(s)",
        education: "Bachelor's in Statistics, Mathematics, CS, or related field"
    },
    {
        index: 6,
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
        title: "Content Writer",
        rate: '$20-40/hr',
        av: 'Freelancer',
        companyName: "Amazon",
        location: "USA/Remote",
        vacancy: '10',
        hours: "Flexible",
        description: "We are seeking creative content writers to craft compelling product descriptions, blogs, and marketing copy. Ideal candidates write clear, engaging content aligned with brand voice.",
        workplace: "Remote",
        experience: "1 to 3 years(s)",
        education: "Bachelor's in English, Communications, or related field"
    },
    {
        index: 7,
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Tesla_logo.png",
        title: "DevOps Engineer",
        rate: '$1,000-1,400/m',
        av: 'Part Time',
        companyName: "Tesla",
        location: "Berlin, Germany",
        vacancy: '02',
        hours: "20h/week",
        description: "At Tesla, you will automate CI/CD pipelines, improve infrastructure reliability, and collaborate with developers to streamline deployments using tools like Docker, Kubernetes, and Terraform.",
        workplace: "Hybrid",
        experience: "3 to 5 years(s)",
        education: "Bachelor's in Computer Science or equivalent experience"
    },
];